apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-datastore
  labels:
    app: tunnel-datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel-datastore
  template:
    metadata:
      labels:
        app: tunnel-datastore
    spec:
      containers:
        - name: mysql
          image: marcnuri/port-forward
          env:
            - name: REMOTE_HOST
              value: 100.64.10.131
            - name: REMOTE_PORT
              value: "3306"
            - name: LOCAL_PORT
              value: "3306"
          ports:
            - name: mysql
              containerPort: 3306

        - name: cifs
          image: marcnuri/port-forward
          env:
            - name: REMOTE_HOST
              value: 100.64.10.131
            - name: REMOTE_PORT
              value: "445"
            - name: LOCAL_PORT
              value: "445"
          ports:
            - name: cifs
              containerPort: 445

        - name: fileprinters
          image: marcnuri/port-forward
          env:
            - name: REMOTE_HOST
              value: 100.64.10.131
            - name: REMOTE_PORT
              value: "139"
            - name: LOCAL_PORT
              value: "139"
          ports:
            - name: fileprinters
              containerPort: 139
