apiVersion: v1
kind: Endpoints
metadata:
  name: tunnel-datastore-edp
subsets:
  - addresses:
      - ip: 100.64.10.131
    ports:
      - name: ssh
        port: 22
      # - port: 445
      # - port: 137
      # - port: 138
      # - port: 139
