apiVersion: v1
kind: Service
metadata:
  name: tunnel-datastore-svc
spec:
  selector:
    app: tunnel-datastore
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql

    - protocol: TCP
      port: 445
      targetPort: cifs

    - protocol: TCP
      port: 139
      targetPort: fileprinters
