apiVersion: v1
kind: Service
metadata:
  name: mc-server-tikiba-svc
spec:
  selector:
    app: mc-server-tikiba
  ports:
  - port: 25565
    targetPort: mc-tikiba
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-server-tikiba
  name: mc-server-tikiba
  # We wish this deployment to be reloaded
  # when "velocity-config" ConfigMap are updated
  annotations:
    configmap.reloader.stakater.com/reload: "mc-server-tikiba-config"
spec:
  replicas: 1
  # レプリカ数の制御を ScaledObject に任せるため、 replicas は指定しない
  # 参考: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#replicas
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mc-server-tikiba
  template:
    metadata:
      labels:
        app: mc-server-tikiba
    spec:
      nodeName: topi-server02
      # initContainers:
      #   - name: velocity-config-downloader
      #     image: busybox:1.36.1
      #     env:
      #       - name: URL
      #         value: https://raw.githubusercontent.com/topi-banana/k8s_infra/main/manifests/mc-gateway-velocity/config/velocity.toml
      #     volumeMounts:
      #       - name: velocity-config
      #         mountPath: /root/download/velocity.toml
      #         subPath: velocity.toml
      #     command:
      #       - "sh"
      #       - "-c"
      #       - 'wget -O /root/download/config.yml "${URL}"'
      containers:
        - resources:
            requests:
              memory: 4G
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 4G
            - name: DIFFICULTY
              value: "hard"
            - name: MODE
              value: "survival"
            - name: VERSION
              value: 1.20.1
            - name: TYPE
              value: PAPER
            - name: OPS
              value: topi_banana,tikiba7
            - name: PLUGINS
              # tabtps, worldedit, DiscordSRV
              value: https://hangarcdn.papermc.io/plugins/jmp/TabTPS/versions/1.3.18/PAPER/tabtps-spigot-1.3.18.jar, https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar, https://cdn-raw.modrinth.com/data/UmLGoGij/versions/D1NeVd6Q/DiscordSRV-Build-1.26.2.jar
            - name: COPY_CONFIG_DEST
              value: /data
          # https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version
          image: itzg/minecraft-server:java17
          name: mc-server-tikiba
          ports:
            - containerPort: 25565
              name: mc-tikiba
          # startupProbe:
          #   tcpSocket:
          #     port: 25565
          #   # 最大120秒待つ
          #   failureThreshold: 6
          #   periodSeconds: 20
          volumeMounts:
            - name: mc-server-tikiba-config
              mountPath: /config/config/paper-global.yml
              subPath: paper-global.yml
            - name: mc-server-tikiba-config
              mountPath: /config/server.properties
              subPath: server.properties
            - name: mc-server-tikiba-world
              mountPath: /data/world
              subPath: world
            - name: mc-server-tikiba-world
              mountPath: /data/world_the_end
              subPath: world_the_end
            - name: mc-server-tikiba-world
              mountPath: /data/world_nether
              subPath: world_nether
      volumes:
        - name: mc-server-tikiba-config
          configMap:
            name: mc-server-tikiba-config
        - name: mc-server-tikiba-world
          hostPath:
            path: /home/topi/tikiba-world
            type: DirectoryOrCreate
          #nfs:
          #  server: nfs-service.app.svc.cluster.local
          #  path: /tikiba/world
          #persistentVolumeClaim:
          #  claimName: nfs-pvc
