apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-server
  name: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeName: topi-server01
      containers:
        - name: nfs-server
          image: mekayelanik/nfs-server-alpine
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: ALLOWED_CLIENT
              value: 0.0.0.0
            - name: NFS_MOUNT_PORT
              value: 2049
            - name: NFS_ROOT_DIR
              value: /data
          securityContext:
            privileged: true
          ports:
            - name: nfs-server
              containerPort: 2049
          volumeMounts:
            - mountPath: /data
              name: exports
      volumes:
        - name: exports
          hostPath:
            path: /mnt/nfs
            type: DirectoryOrCreate
