# apiVersion: v1
# kind: Secret
# metadata:
#   name: admin-basic-auth
# type: Opaque
# data:
#   # docker run -it --rm httpd:alpine htpasswd -n {user_name}
#   # to base64 convert
#   auth: "dG9waTokYXByMSRFaTlqNHpqZSR1aDJSelBHWUJxbW9jT0QwNmVPRm4xCg=="