apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-server-poteto
  name: mc-server-poteto
  # We wish this deployment to be reloaded
  # when "velocity-config" ConfigMap are updated
  annotations:
    configmap.reloader.stakater.com/reload: "mc-server-poteto-config,mc-server-poteto-vscode-config"
spec:
  # レプリカ数の制御を ScaledObject に任せるため、 replicas は指定しない
  # 参考: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#replicas
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mc-server-poteto
  template:
    metadata:
      labels:
        app: mc-server-poteto
    spec:
      nodeName: topi-server02
      # initContainers:
      #   - name: velocity-config-downloader
      #     image: busybox:1.36.1
      #     env:
      #       - name: URL
      #         value: https://raw.githubusercontent.com/topi-banana/k8s_infra/main/manifests/mc-gateway-velocity/config/velocity.toml
      #     volumeMounts:
      #       - name: velocity-config
      #         mountPath: /root/download/velocity.toml
      #         subPath: velocity.toml
      #     command:
      #       - "sh"
      #       - "-c"
      #       - 'wget -O /root/download/config.yml "${URL}"'
      containers:
        - env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: 1.20.2
            - name: TYPE
              value: PAPER
            - name: OPS
              value: topi_banana
            - name: COPY_CONFIG_DEST
              value: /data
            - name: PLUGINS
              value: >-
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.8.0/PAPER/ViaVersion-4.8.0.jar
          # https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version
          image: itzg/minecraft-server:java17
          name: mc-server-poteto
          ports:
            - containerPort: 25565
              name: mc-poteto
          # startupProbe:
          #   tcpSocket:
          #     port: 25565
          #   # 最大120秒待つ
          #   failureThreshold: 6
          #   periodSeconds: 20
          ports:
            - containerPort: 8080
              name: mc-test-vscode
          volumeMounts:
            - name: mc-server-poteto
              mountPath: /data
            - name: mc-server-poteto-config
              mountPath: /config/config/paper-global.yml
              subPath: paper-global.yml
            - name: mc-server-poteto-config
              mountPath: /config/server.properties
              subPath: server.properties
        - name: vscode-server
          image: codercom/code-server:latest
          volumeMounts:
            - name: mc-server-poteto
              mountPath: /home/coder/mc
            - name: mc-server-poteto-vscode-config
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 8080
              name: mc-poteto-code
      volumes:
        - name: mc-server-poteto-config
          configMap:
            name: mc-server-poteto-config
        - name: mc-server-poteto-vscode-config
          configMap:
            name: mc-server-poteto-vscode-config
        - name: mc-server-poteto
          hostPath:
            path: /home/topi/poteto
            type: DirectoryOrCreate
