apiVersion: v1
kind: Service
metadata:
  name: nfs-server-svc
spec:
  selector:
    app: nfs-server
  type: ClusterIP
  clusterIP: 10.42.20.49
  ports:
    - name: nfs-server
      protocol: TCP
      port: 2049
      targetPort: 2049